### ISSUE TITLE
Index process trying to find a Stemmer for Chinese 

### ISSUE THREAD

**Issue by hunterhector** [dbpedia-spotlight/model-quickstarter#11]
While running the following command trying to build a model for Chinese:

./index_db.sh wdir zh_CN zh/stopwords.list None models/zh

I encountered the following error:

java.lang.reflect.InvocationTargetException
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.codehaus.mojo.exec.ExecJavaMojo$1.run(ExecJavaMojo.java:297)
        at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.ClassNotFoundException: org.tartarus.snowball.ext.NoneStemmer
        at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
        at java.lang.Class.forName0(Native Method)
        at java.lang.Class.forName(Class.java:264)
        at org.dbpedia.spotlight.db.stem.SnowballStemmer.<init>(SnowballStemmer.scala:10)
        at org.dbpedia.spotlight.db.tokenize.TextTokenizerFactory.createTokenizer(TextTokenizerFactory.scala:18)
        at com.diffbot.wikistatsextractor.extractors.ExtractSFAndRedirections.extractAllSurfaceFormsAndRedirection(ExtractSFAndRedirections.java:161)
        at com.diffbot.wikistatsextractor.extractors.Launcher.main(Launcher.java:41)

Apparently, the TokenizerFactory is trying to initialize a Stemmer for Chinese, using the "None" option. This results into a non-existing class "org.tartarus.snowball.ext.NoneStemmer". I am wondering what need to be done to get around this Stemming problem?

**Comment by hunterhector** [comment]
This turns out to be a simple parameter error:

https://github.com/dbpedia-spotlight/dbpedia-spotlight/blob/12329250ce0f7f6180ed6111988477718895f189/core/src/main/scala/org/dbpedia/spotlight/db/tokenize/TextTokenizerFactory.scala#L17

The above factory method will accept "None"  or a Stemmer name. For Chinese, the current script will use a parameter of value $4"Stemmer", where $4 is the stemmer language name, see [L195 in index_db](https://github.com/dbpedia-spotlight/model-quickstarter/blob/master/index_db.sh#L195) and [L214 in index_db](https://github.com/dbpedia-spotlight/model-quickstarter/blob/master/index_db.sh#L214). This will make the parameter be "NoneStemmer", and the factory cannot deal with that.

I have changed $4"Stemmer" into $4 in my case to run the Chinese indexer.

**Comment by hunterhector** [comment]
Well maybe I shouldn't close this so an official fix can be made.

**Comment by sandroacoelho** [comment]
Hi @hunterhector ,

Thank you for debug it :+1: . I will fix ASAP

Best

**Comment by sandroacoelho** [comment]
Dear @hunterhector ,

The bug was fixed. You can get our latest monthly build [here](http://downloads.dbpedia-spotlight.org/monthly_build/models/zh)

Best,

**Comment by hunterhector** [comment]
Thank you! The model should be quite helpful to me as well!
